server:
  port: 8080

spring:
  application:
    name: wms-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/wms
    username: wms
    password: wms

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

